import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "./reset.css";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/Header/Header";
import { QueryProvider } from "@/components/providers/QueryProvider";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={roboto.variable} data-scroll-behavior="smooth">
      <body>
        <QueryProvider>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
